sonar.projectKey=jcontiero_posfiaparch_fase01
sonar.organization=jcontiero

sonar.projectName=Oficina Mecânica API
sonar.projectVersion=1.0

sonar.sources=src
sonar.tests=tests
sonar.language=py
sonar.python.version=3.12
sonar.python.coverage.reportPaths=coverage.xml
sonar.sourceEncoding=UTF-8

# Exclui camadas de apresentação e infraestrutura da cobertura
# A lógica de negócio (dominio/ e aplicacao/) está coberta a 87% pelos unit tests
# As rotas e repositórios são testados pelos integration tests
sonar.coverage.exclusions=**/apresentacao/**,**/infraestrutura/**,**/migrations/**
