"""Initial migration

Revision ID: 28c30c8cd20c
Revises:
Create Date: 2026-07-08 12:36:12.176833

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import src.atendimento.infraestrutura.modelos

# revision identifiers, used by Alembic.
revision: str = "28c30c8cd20c"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "clientes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("nome", sa.String(), nullable=False),
        sa.Column(
            "cpf",
            src.atendimento.infraestrutura.modelos.CPFType(length=11),
            nullable=True,
        ),
        sa.Column(
            "cnpj",
            src.atendimento.infraestrutura.modelos.CNPJType(length=14),
            nullable=True,
        ),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("telefone", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_clientes_cnpj"), "clientes", ["cnpj"], unique=True)
    op.create_index(op.f("ix_clientes_cpf"), "clientes", ["cpf"], unique=True)
    op.create_table(
        "pecas",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("nome", sa.String(), nullable=False),
        sa.Column("codigo", sa.String(), nullable=False),
        sa.Column("preco_unitario", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("quantidade_disponivel", sa.Integer(), nullable=False),
        sa.Column("quantidade_minima_alerta", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_pecas_codigo"), "pecas", ["codigo"], unique=True)
    op.create_table(
        "servicos",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("nome", sa.String(), nullable=False),
        sa.Column("descricao", sa.String(), nullable=False),
        sa.Column("preco_base", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("tempo_estimado_minutos", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_servicos_nome"), "servicos", ["nome"], unique=False)
    op.create_table(
        "usuarios",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("senha_hash", sa.String(), nullable=False),
        sa.Column(
            "perfil",
            sa.Enum("ADMIN", "MECANICO", name="perfil_usuario"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_usuarios_email"), "usuarios", ["email"], unique=True)
    op.create_table(
        "veiculos",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("cliente_id", sa.UUID(), nullable=False),
        sa.Column(
            "placa",
            src.atendimento.infraestrutura.modelos.PlacaType(length=8),
            nullable=False,
        ),
        sa.Column("marca", sa.String(), nullable=False),
        sa.Column("modelo", sa.String(), nullable=False),
        sa.Column("ano", sa.Integer(), nullable=False),
        sa.Column("cor", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["cliente_id"],
            ["clientes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_veiculos_placa"), "veiculos", ["placa"], unique=True)
    op.create_table(
        "ordens_de_servico",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("cliente_id", sa.UUID(), nullable=False),
        sa.Column("veiculo_id", sa.UUID(), nullable=False),
        sa.Column("descricao_problema", sa.String(), nullable=False),
        sa.Column("laudo_diagnostico", sa.String(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "RECEBIDA",
                "EM_DIAGNOSTICO",
                "AGUARDANDO_ORCAMENTO",
                "AGUARDANDO_APROVACAO",
                "EM_EXECUCAO",
                "SERVICOS_CONCLUIDOS",
                "FINALIZADA",
                "ENTREGUE",
                "CANCELADA",
                name="status_os",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("valor_orcamento", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("criada_em", sa.DateTime(timezone=True), nullable=False),
        sa.Column("atualizada_em", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["cliente_id"],
            ["clientes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["veiculo_id"],
            ["veiculos.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "itens_peca",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("os_id", sa.UUID(), nullable=False),
        sa.Column("peca_id", sa.UUID(), nullable=False),
        sa.Column("descricao", sa.String(), nullable=False),
        sa.Column("quantidade", sa.Integer(), nullable=False),
        sa.Column("preco_unitario", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.ForeignKeyConstraint(
            ["os_id"],
            ["ordens_de_servico.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "itens_servico",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("os_id", sa.UUID(), nullable=False),
        sa.Column("servico_id", sa.UUID(), nullable=False),
        sa.Column("descricao", sa.String(), nullable=False),
        sa.Column("preco_unitario", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("observacao", sa.String(), nullable=True),
        sa.Column("concluido", sa.Boolean(), nullable=False),
        sa.Column("concluido_em", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["os_id"],
            ["ordens_de_servico.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("itens_servico")
    op.drop_table("itens_peca")
    op.drop_table("ordens_de_servico")
    op.drop_index(op.f("ix_veiculos_placa"), table_name="veiculos")
    op.drop_table("veiculos")
    op.drop_index(op.f("ix_usuarios_email"), table_name="usuarios")
    op.drop_table("usuarios")
    op.drop_index(op.f("ix_servicos_nome"), table_name="servicos")
    op.drop_table("servicos")
    op.drop_index(op.f("ix_pecas_codigo"), table_name="pecas")
    op.drop_table("pecas")
    op.drop_index(op.f("ix_clientes_cpf"), table_name="clientes")
    op.drop_index(op.f("ix_clientes_cnpj"), table_name="clientes")
    op.drop_table("clientes")
    # ### end Alembic commands ###
