apiVersion: v1
kind: ConfigMap
metadata:
  name: oficina-api-config
  namespace: oficina-api
  labels:
    app: oficina-api
    tier: api
    env: production
data:
  ALGORITHM: "HS256"
  TOKEN_EXPIRE_HORAS: "8"
  SMTP_HOST: "smtp.gmail.com"
  SMTP_PORT: "587"
  EMAIL_REMETENTE: "noreply@suaoficina.com"
  EMAIL_ADMIN: "admin@suaoficina.com"
  ADMIN_EMAIL: "admin@oficina.com"
