apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: oficina-api
  labels:
    app: oficina-api
    tier: db
    env: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oficina-api
      tier: db
  template:
    metadata:
      labels:
        app: oficina-api
        tier: db
        env: production
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
              name: postgres
          env:
            - name: POSTGRES_DB
              value: "oficina_db"
            - name: POSTGRES_USER
              value: "oficina_user"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: oficina-api-secret
                  key: ADMIN_SENHA
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - oficina_user
                - -d
                - oficina_db
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - oficina_user
                - -d
                - oficina_db
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
