apiVersion: v1
kind: Service
metadata:
  name: oficina-api
  namespace: oficina-api
  labels:
    app: oficina-api
    tier: api
    env: production
spec:
  type: ClusterIP
  selector:
    app: oficina-api
    tier: api
  ports:
    - port: 80
      targetPort: 8000
      name: http
